### ISSUE TITLE
documenting where preferences are found

### ISSUE THREAD

**Issue by ronburk** [wshanks/Zutilo#138]
In:

https://github.com/willsALMANJ/Zutilo/blob/master/docs/COMMANDS.md

the note "(accessed from the same menu as Zotero's preferences)" confused me. Using Firefox and Zotero 5.x, I eventually found that the Zutilo preferences were instead in Tools|Zutilo preferences..., whereas the Zotero preferences were in Edit|Preferences.

**Comment by willsALMANJ** [comment]
Yes, it used to be in Edit|Preferences before https://github.com/willsALMANJ/Zutilo/commit/2ee26a7d3ea940a93ea144f541bb42e343a37953 (the Zotero developer requested that extension preferences be moved there). The documentation needs to be updated to match the new location.

**Comment by qqobb** [comment]
I think this issue can be closed. It has been addressed by https://github.com/wshanks/Zutilo/commit/4f2be986cf934a3b08541f485ad7e9e6906f02f2.
