### ISSUE TITLE
modify full path (without invoking the wrong path)

### ISSUE THREAD

**Issue by maxmaronna** [wshanks/Zutilo#156]
Hello
I have a lot of PDFs with wrong paths, in same cases related to one PC, and in some cases to another PC....so, is there a way to just modify full path to several PDFs at the same time (without invoking the partial path for each case)?
Thanks in advance
max

**Comment by wshanks** [comment]
No, but you can select attachments with old paths that do not match the partial path and they won't be modified. So you could select all the attachments and run "modify attachment paths" twice to handle the two cases. Also, see #173 for a suggestion on how to run custom Javascript from Zotero if you want to try to tune the logic to your case.
