### ISSUE TITLE
Feature-Request: Add shortcut keys for superscript and subscript 

### ISSUE THREAD

**Issue by northword** [wshanks/Zutilo#177]
First of all, thank you for developing such a good plugin!  And I have a small idea. 

## Application scenario

For example, i have a item named "Influence of surface active groups on SO2 resistance of birnessite for low-temperature NH3-SCR", and when I generate citations in Word, I need to make "2" the subscript. In order to achieve this, I had to manually add `<sub>`, which is very troublesome. 

![image](https://user-images.githubusercontent.com/44738481/106015919-ea5cb700-60f9-11eb-9f9b-6c1d4d515ba5.png)
Fig. 1 item without sub

![image_no_sub](https://user-images.githubusercontent.com/44738481/106015805-cd27e880-60f9-11eb-97e5-d3f2e9a8be4b.png)
Fig. 2 Bibliograohy without sub

![image](https://user-images.githubusercontent.com/44738481/106016190-2a239e80-60fa-11eb-8f92-92cdf6b889ec.png)
Fig. 3 item with sub

![image](https://user-images.githubusercontent.com/44738481/106016240-360f6080-60fa-11eb-9c29-df688720934c.png)
Fig. 4 Bibliograohy with sub

## Solution 

When I select `2` and press `ctrl+=`, Zutilo can replace it with `<sub>2</sub>`. 
Similarly, when I press `ctrl+shift+=`， replace it with `<sup>2</sup>`

**Comment by IdoBar** [comment]
Following this thread, I would like to create a similar shortcut for adding other HTML tags around selected text.

**Comment by northword** [comment]
solved by https://github.com/northword/zotero-format-metadata
