### ISSUE TITLE
ZotFile Extract Annotations shortcut does not work

### ISSUE THREAD

**Issue by carbeer** [wshanks/Zutilo#183]
I assigned a shortcut to the ZotFile "Extract Annotations" feature and applied the changes. However, the shortcut does not appear to have any effect.

Zutilo V3.8.0
ZotFile V5.0.16
Zotero V5.0.95
Running on Linux Mint 19.3 Cinnamon (based on Ubuntu 18.04)

When I trigger "Extract Annotations" through the menu, everything still works fine. Other Zutilo shortcuts are still functional. Restarting Zotero didn't help.

**Comment by wshanks** [comment]
Yes, it looks like there was a typo when the feature was added. Not sure how that got through.

**Comment by carbeer** [comment]
Thank you for fixing this so quickly. This is  super useful functionality! :blush:
