### ISSUE TITLE
Shortcut not work (all software are latest version)

### ISSUE THREAD

**Issue by ydprtm** [wshanks/Zutilo#187]
Hi there,

I'm new to Zotero. Just installed it and this great addon, trying to replace Endnote.

My concern is any possible difference in the output style in this new software. So I frequently preview the Style Editor to check and find this addon to define a shortcut to open the Style Editor. But, none of the shortcuts I defined worked...

FYI, two shortcuts I defined:

- Open the style editor: Ctrl+Shift+P (also tried Ctrl+F12 in the beginning)
- Items pane next tab: F6

My environment info as below:

- Latest Zotero for Windows downloaded from the official site, version 5.0.96.
- Latest Zutilo version 3.8.1.
- Windows 10 Home edition, 20H2, version 19042.867.
- Message in error console after pressing the defined shortcut (Ctrl+Shift+P) as below:

`[JavaScript Error: "ReferenceError: window is not defined" {file: "chrome://zotero/content/preferences/preferences.js" line: 144}]
openInViewer@chrome://zotero/content/preferences/preferences.js:144:9
keys.shortcuts.openStyleEditor@chrome://zutilo/content/keys.js:338:5
createKey/<@chrome://zutilo/content/zoteroOverlay.js:1229:17`

PS., Zotero is wired. The Error console has the "Copy" option for each message item after right-click, but never works!

**Comment by qqobb** [comment]
I could reproduce your issue with the Open Style Editor shortcut. While I don't understand why it's broken, I found a simple fix.

The Open Style Editor shortcut has been added with PR https://github.com/wshanks/Zutilo/pull/44. The relevant Zutilo code is [here](https://github.com/wshanks/Zutilo/blob/52b37cd58543df462519fa8f909b8413b188cd2e/addon/chrome/content/zutilo/keys.js#L330-L340). It's using the code from https://github.com/wshanks/Zutilo/issues/41#issuecomment-136248872, which still works in Zotero's [JavaScript API](https://www.zotero.org/support/dev/client_coding/javascript_api). However, when the `openInViewer` command is executed in Zutilo, it seems that [these lines](https://github.com/zotero/zotero/blob/ed70b404add4031a8408cf4ab2e62197a4902b38/chrome/content/zotero/preferences/preferences.js#L144-L145) throw a "window undefined" error. I don't understand much about this, but I suspect that some of the Fx60 changes (see, e.g., [here](https://github.com/zotero/zotero/commits/master/chrome/content/zotero/preferences/preferences.xul)) might be at the root of this issue.

Luckily, there's a simple fix that doesn't require calling the `openInViewer` command. We can now call the `openStyleEditor()` function ([here](https://github.com/zotero/zotero/blob/ed70b404add4031a8408cf4ab2e62197a4902b38/chrome/content/zotero/standalone/standalone.js#L806-L812)) from the Tools -> Developer menu ([here](https://github.com/zotero/zotero/blob/ed70b404add4031a8408cf4ab2e62197a4902b38/chrome/content/zotero/standalone/standalone.xul#L336-L339)).

I'll create a pull request for this fix. In the meantime, you can use Alt+T+D+S as a shortcut.

> Items pane next tab: F6

This will most likely not work, see https://github.com/wshanks/Zutilo/issues/122.

> The Error console has the "Copy" option for each message item after right-click, but never works!

Yes, this seems to be a Zotero bug. You can select the message and use Ctrl+C instead. Zotero's desktop client is currently based on Firefox. The Zotero developers are planning to update the Firefox base later this year, see [here](https://forums.zotero.org/discussion/comment/376000#Comment_376000). Maybe this bug will be resolved when that update happens.
