### ISSUE TITLE
shortcuts menu empty on macOS

### ISSUE THREAD

**Issue by leonmoonen** [wshanks/Zutilo#216]
Hi,

[ Zutilo version v3.10.0 / Zotero version 5.0.96.3 / macOS Big Sur 11.6.2 ] 

I'm using v3.10.0 and noticed that my shortcut menu is completely empty (i.e. not listing any functions):
<img src="https://user-images.githubusercontent.com/2410711/153204922-815aaade-ad68-4c47-a57c-17c6f616283f.png" width=50%>
I seem to remember this was not the case in an earlier version; in fact I had set up a shortcut to pin a BetterBibtex key that (initially) was still operational while being in this situation.

A first uninstall / reinstall did not change anything (but kept the existing shortcut). Next, I uninstalled v3.10.0 and also removed "~/Library/Application Support/Zotero/Profiles/kk3b3wqa.default/extensions/staged/zutilo@www.wesailatdawn.com" and reinstalled (with the idea this might do more initialization). This did also not solve the empty shortcut menu (but removed the existing shortcut, as expected).

Are there other types of resets/reinstalls can I do to revert the shortcut menu to it's original state?

thanks,
Leon

**Comment by qqobb** [comment]
See https://github.com/wshanks/Zutilo/issues/107#issuecomment-520676251 for how to fix this.

We should have a proper fix for this soon. The issue seems to be with the character encoding of the preferences. (I'll submit a PR.)

Duplicate of #195.

**Comment by leonmoonen** [comment]
solved!  thanks 🙏🏼
