### ISSUE TITLE
How to customize the label "alt 1" and "alt 2

### ISSUE THREAD

**Issue by redleafnew** [wshanks/Zutilo#218]
hi all,
I would like to use the <code>QuickCopy items (alt 1)</code> and  <code>QuickCopy items (alt 2)</code> command. Is it possible to change the label <code>alt 1</code> or <code>alt 2</code> to other name like the journal name<code> QuickCopy items (Nature)</code>, <code>QuickCopy items (Science)</code>?

Many thanks.

**Comment by qqobb** [comment]
Currently, this isn't possible. But adding such an option seems like a good idea. This is a duplicate of #121.

For now, you might want to set up keyboard shortcuts that you can remember easily. E.g., Alt+Shift+N for Nature and Alt+Shift+S for Science.

Please comment in #121 if you have suggestions regarding an implementation. As discussed there, we could add some menu with a GUI derived from Zotero's [Export preferences pane](https://www.zotero.org/support/preferences/export). Alternatively, we could simply add some related hidden Zutilo preferences. Users could then run a script in Zotero's JavaScript API that sets up QuickCopy translator preferences and labels.

**Comment by redleafnew** [comment]
Many thanks.
