### ISSUE TITLE
Add Note would be more useful if parent item were inferred

### ISSUE THREAD

**Issue by ronburk** [wshanks/Zutilo#223]
Thanks for a great tool!

I tend to add one child note per interesting passage as I read a book.
When I finish typing a note, the focus is in the note pane. So I then have
to swish the mouse left to select the parent item in the item pane, then
swish the mouse back to click the "Add" button beneath the "Notes" tab.

I had hoped to use Zutilo to bind (e.g.) Ctrl-N to "Add Note" so that I would
not have to have my hands leave the keyboard to add the next  note. Unfortunately,
Zutilo complains with "Please select one (and only one) regular item."

Seems like in this situation Zutilo could notice that what's selected in the
item pane is a child note and infer that the user almost certainly wants
to add another child note to the same parent item.

**Comment by qqobb** [comment]
The shortcut you're looking for exists in Zotero. The default [keyboard shortcut](https://www.zotero.org/support/kb/keyboard_shortcuts) for creating a new note is Ctrl+Shift+O. I changed mine to Ctrl+Shift+N, switching N and O in the [Advanced pane](https://www.zotero.org/support/preferences/advanced#shortcuts) of the Zotero preferences. You can use it to create another child note even when the focus is in the note pane. Here's a related (old) discussion: https://forums.zotero.org/discussion/24666/improve-new-note-shortcut.

We could perhaps change Zutilo's shortcut or remove it. The [command reference](https://github.com/wshanks/Zutilo/blob/master/docs/COMMANDS.md#navigating-the-ui-and-editing-items-via-keyboard-shortcuts) mentions that there's a Zotero shortcut for this.

**Comment by ronburk** [comment]
Thank you!!!  Some piece of software had already taken over Ctrl-Shift-O on my box to display a mini-display of system resources, so I did the same as you and can now happily Ctrl-Shift-N to a new note!
