### ISSUE TITLE
Display items in subcollections of currently displayed collection

### ISSUE THREAD

**Issue by ackern** [wshanks/Zutilo#227]
I don't know if I'm in the right place. I have a question, not a feature request. Does Zotilo have any easy way to make Zotero display the items in subcollections of the currently displayed collection? The only way I know is to toggle the preference extensions.zotero.recursiveCollections  which does what I want except that it's too many clicks. Can Zotilo set a shortcut for it or in some other way achieve the same effect?

**Comment by qqobb** [comment]
Zotero's "Show Items from Subcollections" preference can be toggled in the View menu. You can also use the keyboard for this: "Alt+V" -> "ArrowUp" -> "Enter".

Currently, there's no Zutilo shortcut for this, but I'm not sure it's worth adding one. If you're switching the option frequently, Alt+V will show you the current state, which could be useful, I think. With a Zutilo shortcut you'd be blind about the current state of the option. Alt+V is also easy to remember.

**Comment by qqobb** [comment]
I think Alt+V is the best option for this as explained above, so I'll close the issue.

Please let us know if you think there's a better solution.
