### ISSUE TITLE
keyboard shortcuts [zotero 6]

### ISSUE THREAD

**Issue by tjallemaal** [wshanks/Zutilo#230]
zotero auto-updated to version 6.
i didn't like the new design anyways.
but what's more: my zutilo shortcuts stopped working:

in the preferences, the shortcuts are still in place. but they just don't work anymore ...

any idea what i could do ?

thx alot

**Comment by qqobb** [comment]
Could you be more specific about what's broken? Which function are you referring to and what's the shortcut?

- Zutilo generally works well in Zotero 6.

- Note that Alt+V [opens the View menu](https://github.com/wshanks/Zutilo/issues/222) now.

- Please make sure that you've installed the latest Zutilo version. Download the latest XPI file from the [releases page](https://github.com/wshanks/Zutilo/releases), select "Tools" -> "Add-ons", then select "Install Add-on From File" in the gear menu in the top right of the window to install it.

BTW, Zotero's new PDF reader is optional. You can disable it in the General pane of the Zotero preferences. The [open-pdf plugin](https://github.com/retorquere/zotero-open-pdf) can help if you want to use Zotero's PDF reader along with an external viewer. It adds a new option "Open in External/Internal Viewer" to the item's context menu.

**Comment by tjallemaal** [comment]
<img width="652" alt="Screenshot 2022-07-20 at 09 24 05" src="https://user-images.githubusercontent.com/69585777/179921953-dd3d9fd5-45c0-4e3d-a05f-cca957f624ac.png">

cmd+2  is my shortcut for the items pane: it doesn't react since the last update to zotero 6 ...

**Comment by tjallemaal** [comment]
actually none of them work. cmd+1  or cmd+4  are dead as well

**Comment by qqobb** [comment]
> actually none of them work. cmd+1 or cmd+4 are dead as well

You might have to use different shortcuts. The shortcuts `Cmd`+`1` through `9` are used for [switching tabs](https://www.zotero.org/support/kb/keyboard_shortcuts#moving_between_tabs) in Zotero 6.

See also https://github.com/wshanks/Zutilo/issues/226#issuecomment-1140048813 for related suggestions.

**Comment by qqobb** [comment]
It seems to me that the issue was resolved, so I'm closing it. Please let us know if this isn't the case.
