### ISSUE TITLE
Why no more than 2 alternative copies?

### ISSUE THREAD

**Issue by tobiasBora** [wshanks/Zutilo#231]
I would like to have many different copies: copy the key of the bibtex entry, copy the bibtex, copy the biblatex, copy the bibjson (I need all of these depending on what I'm doing) and even sometimes copy the text version to copy/paste in email/word/libre office.

Unfortunately, as far as I can see there are only 3 quick copies available (quick copy, alt 1, alt2). Would it be possible to add more quick copies options? In the meantime is there a workaround?

**Comment by wshanks** [comment]
Sorry, this is something that needs to be documented better (i.e. at all). You can change the number of quick copy items by changing the `extensions.zutilo.copyItems_alt_total` preference in the config editor (Zotero Preferences -> Advanced -> Config Editor; accept the risk; search for copyItems_alt_total).

The only documentation for this right now is that I mentioned it in [this comment](https://github.com/wshanks/Zutilo/pull/135#issuecomment-636136857) and https://github.com/wshanks/Zutilo/pull/146.

**Comment by tobiasBora** [comment]
Great, thanks a lot, I'll close this! Btw, is there any way to rename the entries not to get confused with many "Alt copy N"?

**Comment by qqobb** [comment]
> Btw, is there any way to rename the entries not to get confused with many "Alt copy N"?

Not currently, but it's planned, see #121. For now, I'd recommend setting up keyboard shortcuts that you can remember.
