### ISSUE TITLE
Feature request: Zotero link also to work on iOS

### ISSUE THREAD

**Issue by gabrielparriaux** [wshanks/Zutilo#235]
Hello,

It’s really cool to be able to use the "copy zotero link" feature to be able to introduce into other documents direct links to entries from Zotero database!

As an iOS version of Zotero now exists, it would be great if this feature were also working on the iOS version! I tried, but the link doesn’t seem to be recognized on an iPad. 

Do you know if it would be possible to have a same structure of link that would work on a Mac computer and on an iPad?

Thanks a lot,

Gabriel

**Comment by qqobb** [comment]
The zotero:// links are handled by your operating system and Zotero, so there's not much Zutilo can do here. Zutilo just adds a method to copy the links. If you're using Zotero's web library, you could perhaps use Zutilo's "Copy Zotero URI" function.

You'd need to check about this on the Zotero forums:

[iOS beta feature request: deep linking (i.e. zotero://select schema) to open in iOS Zotero app - Zotero Forums](https://forums.zotero.org/discussion/89272/ios-beta-feature-request-deep-linking-i-e-zotero-select-schema-to-open-in-ios-zotero-app)

**Comment by gabrielparriaux** [comment]
Sure, thanks a lot @qqobb! You’re right, it’s a matter of Zotero to include it to their iOS app! Thanks for the link also, I will comment there.
