### ISSUE TITLE
快捷键无反应

### ISSUE THREAD

**Issue by Jiyuanqing** [wshanks/Zutilo#245]
设定Crtl+1和Crtl+2用来显示/隐藏分类面板和条目面板，但在使用中zutilo没有反应，请问该如何解决？已尝试卸载zutilo后重新载入，但问题并没有解决。
<img width="755" alt="iShot_2022-12-16_20 50 48" src="https://user-images.githubusercontent.com/113078110/208116493-38bd5f1b-0e28-48b5-a4b9-467dafc8afe2.png">

**Comment by qqobb** [comment]
The shortcuts `Cmd`+`1` through `9` are used for [switching tabs](https://www.zotero.org/support/kb/keyboard_shortcuts#moving_between_tabs) in Zotero 6.

See also [#226 (comment)](https://github.com/wshanks/Zutilo/issues/226#issuecomment-1140048813) for related suggestions.

**Comment by Jiyuanqing** [comment]
感谢您的回复！在设置快捷键的时候，我特意避免将“cmd+数字”设置为zutilo的快捷键，而“alt+数字”容易出现乱码，所以使用“crtl+数字”的组合是最佳选择。我发现在刚打开zotero的时候，还没有加载完全部条目之前使用“crtl+1”是有效果的，但如果等全部条目加载完“crtl+1”就失效了，这个情况在今天更新完Jasminum 0.2.4这个插件后得到解决。我想可能是插件之间存在冲突，不过更新完后问题已解决！再次感谢您的关注！谢谢！
