### ISSUE TITLE
"Copy select item links" does not appear in Zutile or Zotero's context menus even after configuring that in Zutilo preferences

### ISSUE THREAD

**Issue by rodrigodesalvobraz** [wshanks/Zutilo#263]
"Copy select item links" does not appear in Zutile or Zotero's context menus even after configuring that in Zutilo preferences:

Zotero context menu:
![image](https://github.com/wshanks/Zutilo/assets/12362395/1914b14d-5564-4cf7-b5bd-a2b7b7a3b1f6)
![image](https://github.com/wshanks/Zutilo/assets/12362395/d2b61ccb-7dcd-4171-956a-0df5e257de28)

Zutilo context menu:
![image](https://github.com/wshanks/Zutilo/assets/12362395/8c2f88e8-e732-4015-b1e5-986ccd3ea987)
![image](https://github.com/wshanks/Zutilo/assets/12362395/2cbfbaa4-ba6e-489a-b589-74c9329ad6f7)

Zotero version 6.0.30
Zutilo version 3.10.0
Few last messages in Error Console are:
- [JavaScript Warning: "Key event not available on some keyboard layouts: key=“i” modifiers=“accel shift alt” id=“key_importFromClipboard”" {file: "chrome://zotero/content/standalone/standalone.xul" line: 0}]
- [JavaScript Warning: "Error in parsing value for ‘max-width’.  Declaration dropped." {file: "chrome://zotero/content/standalone/standalone.xul" line: 0}]
- [JavaScript Warning: "Error in parsing value for ‘width’.  Declaration dropped." {file: "chrome://zotero/content/standalone/standalone.xul" line: 0}]

**Comment by vwrk** [comment]
You have acitvated the wrong option. Instead of `Copy select collection link` you have to chose `Copy select item link` which is located more to the top.

**Comment by rodrigodesalvobraz** [comment]
Thank you!
