### ISSUE TITLE
"Create Book Section" abstract

### ISSUE THREAD

**Issue by quickfold** [wshanks/Zutilo#89]
"Create Book Section" is extremely useful for me. Currently, it leaves any book abstract in the 'abstract' field for the section, but the book abstract is obviously not a good abstract for any particular chapter, especially in an anthology. I would like if it cleared the abstract field for the book section. Thanks!

**Comment by willsALMANJ** [comment]
That should be an easy change. I could see arguments both ways for the abstract, but I am fine with changing the behavior like you suggest

**Comment by qqobb** [comment]
@quickfold: Zotero added its own "Create Book Section" function which clears the Abstract field, see https://github.com/zotero/zotero/issues/2796. I'll therefore close this issue.

(In the future, Zutilo's keyboard shortcut could be set such that it'll use Zotero's function.)
