### ISSUE TITLE
Create book section: author => bookauthor not working

### ISSUE THREAD

**Issue by denismaier** [wshanks/Zutilo#94]
Create book section is described as follows: "The new item is created by duplicating the book item and changing its type to book section. Author entries for the book item are converted to "book author" entries for the new book section item. The new book section item is added as a related item to the original book item. Finally, the title textbox for the new item is focused so that a new title for the book section may be entered."

This basically works, but "authors" are not converted to "book author" for me.

**Comment by willsALMANJ** [comment]
Hmm, I see the same thing. However, I can't see a way to get the field to change to "book author" at all. When I click on it, I only see "Author", "Contributor", "Editor", "Reviewed Author", and "Translator". When I look at the code for Zotero I still see "book author" supported for "book section" item types in `resource/schema/system.sql`. If you see the same thing, you could try asking in the Zotero forum or opening an issue in Zotero repo. The Zutilo code is still nominally changing the type to "book author" but it seems like that is not supported in Zotero at the moment.

**Comment by demai** [comment]
Hmm, that's strange. In the GUI, I do have "Buchautor" (book author in German) here.

**Comment by willsALMANJ** [comment]
I tried on a different computer and I do see "book author" as an option but not getting selected by Zutilo. I will have to look into it more there. I'm not sure why the other system doesn't show the "book author" option.

**Comment by qqobb** [comment]
It seems that the creator type modification had some errors, see https://github.com/zotero/zotero/issues/2732#issuecomment-1203117086.

@denismaier: Zotero added its own "Create Book Section" function which performs the change from author to book author, as you suggested. I'll therefore close this issue.
